apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: postgres
    url: host.docker.internal:5432
    user: nexus
    secureJsonData:
      password: nexus
    jsonData:
      database: nexus
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
      postgresVersion: 1400
      timescaledb: false
    isDefault: false
    editable: false